---
- name: Check WiFi card status
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Get WiFi adapter name using Get-WmiObject
      win_shell: |
        Get-WmiObject Win32_NetworkAdapter | Where-Object { $_.NetConnectionID -like "*Wi-Fi*" } | Select-Object -ExpandProperty NetConnectionID
      register: wifi_adapter_name
      changed_when: false

    - name: Extract WiFi adapter_name
      set_fact:
        wifi_adapter_cleaned: "{{ wifi_adapter_name.stdout.splitlines()[0] | trim }}"

    - name: Display WiFi adapter output for debugging
      debug:
        msg: "Cleaned Adapter Name: {{ wifi_adapter_cleaned }}"

    - name: Check WiFi card status
      win_shell: |
        Get-NetAdapter -Name "{{ wifi_adapter_cleaned }}" | Select-Object -ExpandProperty Status
      register: wifi_status
      when: wifi_adapter_name.stdout != ""

    - name: Display WiFi status
      debug:
        msg: "WiFi adapter status: {{ wifi_status.stdout if wifi_adapter_name.stdout != '' else 'No WiFi adapter found' }}"

    - name: Fail if WiFi is enabled
      fail:
        msg: "Security measure absent: WiFi is enabled"
      when: wifi_adapter_name.stdout != ''
